version: "3.9"

services:
  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./config:/mnt/config # loki-config.yaml ada di sini
      - ./loki-data:/tmp/loki/
    restart: unless-stopped
    user: root
    environment:
      - TZ=Asia/Jakarta

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    command:
      - -config.file=/mnt/config/promtail-config.yaml
      - -config.expand-env=true
    depends_on:
      - loki
    volumes:
      - ./config:/mnt/config # promtail-config.yaml di sini
      - /var/log:/var/log # membaca log system
    ports:
      - "1510:1510/udp" # Syslog dari router network devices
      - "1510:1510/tcp"
      - "1511:1511/udp" # Syslog dari switch network devices
      - "1511:1511/tcp"
      - "1512:1512/udp" # Syslog dari access point devices
      - "1512:1512/tcp"
      - "2514:2514/udp" # Syslog dari servers
      - "2514:2514/tcp"
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
