services:
  ryu-controller:
    # image: sdn-controller:1.0.0
    build: .
    container_name: sdn_controller
    environment:
      CONTROLLER_PORT: 9090 # Port Ryu Controller
      SERVER_AGENT_API_PORT: 8500 # Port Koneksi Server Agent API
      POSTGRES_HOST: 192.168.221.133 # IP/HOST dari Postgresql DB
      POSTGRES_PORT: 5432 # Port Postgresql DB
      POSTGRES_DB: sdn_controller # Nama DB
      POSTGRES_USER: admin # User DB
      POSTGRES_PASSWORD: admin # Password User DB
      WAZUH_API_URL: # URL Wazuh Manager API
      WAZUH_API_USER: # Username Wazuh Manager API
      WAZUH_API_PASSWORD: # Password Wazuh Manager API
      WAZUH_INDEXER_URL: # URL Wazuh Indexer
      WAZUH_INDEXER_USER: # Username Wazuh Indexer
      WAZUH_INDEXER_PASSWORD: # Password Wazuh INdexer
      LOKI_URL: # URL Loki
      SYSLOG_SERVER: 192.168.221.133 # URL Syslog Server alias Loki-Promtail
      PASSWORD_ENCRYPTION_KEY: T6xlIWsVK6Oit9l1CQhHBtJDMPuLsDaV0Vjj20Bpcvw= # Key Enkripsi Password Kredensial Devices
      TZ: Asia/Jakarta
    ports:
      - "9090:9090" # Sesuaikan Port ini dengan CONTROLLER_PORT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 5m
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - ./snmp:/opt/prometheus
    restart: unless-stopped
    #    networks:                 #  Production
    #      - sdn_network
    network_mode: host #  debugging test

networks:
  sdn_network:
    name: sdn_network
