@version: 3.36

source s_cisco {
    udp(ip(0.0.0.0) port(15111));
};

rewrite r_fix_timestamp {
    subst("([A-Z][a-z]{2}\\s+[ 0-9]{1,2}\\s+[0-9]{2}:[0-9]{2}:[0-9]{2})\\.[0-9]+:", "\\1:", value("MESSAGE") flags("global"));
};

template t_rfc3164 {
    # template("<${PRI}>${DATE} ${HOST} ${PROGRAM}: ${MESSAGE}\n");
    template("<${PRI}>${DATE} ${PROGRAM} ${HOST}: ${MESSAGE}\n");
};

destination d_promtail {
    udp("promtail" port(1511) template(t_rfc3164));
};

log {
    source(s_cisco);
    rewrite(r_fix_timestamp);
    destination(d_promtail);
};
